  name: "rf_anomaly"
  version_policy {
    latest {
      num_versions: 1
    }
  }
  max_batch_size: 277777
  input {
    name: "input__0"
    data_type: TYPE_FP32
    dims: 52
  }
  output {
    name: "output__0"
    data_type: TYPE_FP32
    dims: 2
    label_filename: "labels.txt"
  }
  instance_group {
    name: "rf_anomaly_0"
    count: 1
    gpus: 0
    kind: KIND_GPU
  }
  dynamic_batching {
    preferred_batch_size: 277777
    max_queue_delay_microseconds: 100
  }
  optimization {
    input_pinned_memory {
      enable: true
    }
    output_pinned_memory {
      enable: true
    }
  }
  parameters {
    key: "model_type"
    value {
      string_value: "xgboost_json"
    }
  }
  parameters {
    key: "output_class"
    value {
      string_value: "true"
    }
  }
  parameters {
    key: "predict_proba"
    value {
      string_value: "true"
    }
  }
  parameters {
    key: "storage_type"
    value {
      string_value: "AUTO"
    }
  }
  parameters {
    key: "threshold"
    value {
      string_value: "0.5"
    }
  }
  backend: "fil"
